sudo: false
language: java
addons:
  apt:
    packages:
    - oracle-java8-installer
script: "
  if [ ${TRAVIS_PULL_REQUEST} = 'false' ];
  then
    echo \"== MAIN build ==\";
    ./gradlew clean test uploadArchives;
  else
    echo \"== PULL build ==\";
    ./gradlew clean test;
  fi
"
jdk:
- oraclejdk8
env:
  global:
  - secure: T3wURMX/z856oijFHEkOPlxOP/RLXymUYrJqLn22I4R3CngW/xCFgwBsIUJqIQteoVA6PVID9qKCfM0b7IHqP+lx3XNTS2DezhwQpr/EL4gcNH39uKaOBFmzaK5cXW6jjZA/I/7Kyrv3+XMKfUQkCYj3zzm3j4MXQoYZ3Zbj+MLGfcZcfhsFK5O6htah7QYOGubDdqeHVqa8roj6myvSy/cbZtBYk34svSn1Y9XSuW0F3lsMV1qgoaGFpFDK68ch4y+yt7OGMvQ4XBiS6FHt3IL7QqZccHDPqR9FNai5BMRI77LDUkwt7QeTXNfb+SNY0X3xXHpLIKGu0ZTT6dT9eulgNu9FirfF/ecWEBEGqx/0hve4N5wGeKUQ3POxzzupeEFhlPBhADrUnRAG3acUU+UaGGOxdhHpS25qa08Dqi5x+2feEgz+jhJwdArvUt2RW8/yLK5KDNDVMMDHX5azcNDt92T4P7c0G5JX1VQQempp8aFNMYJ3kdB6na4oGG9ZL8keqR603M+1DtMaW1oWpyaSBf5qYyAHEFJDQNCtGYzsFwp56NsInGaZWwhNjOptb6P/u0bgpXCc1OsUcKpULqAVurqTRuNRxL00hQS74MQ02g6uQp674Ly9zPIoitTKUTsmy1NClvzUJueN41zOHWFfdpFO/SaBj3Zxz/AIG+o=
  - secure: j20pcXMaYOro2+dkxLwoK3ZakDGeqlDZw8jiif48QsrtF7yU7V4drfsTjWjQjVjwJv/Vkco6xaE4dEJxKqc2iQKvCy0sG+DSCe9inBynJbxxmsuPLyODzsX52qgIlXAWoK5G6GJsKmGqdF7ieTXIbcqOe0HXaPqpGi3maKgJdM0yDTURGAKh68eWBtFgFoUkweZivMwgKLyen6X6doqUNSnUwJLslX6WYuDvj6L3jx4Wco5R+tuOfdXiK9bx+EM3WpsyZu4dveW3cXfTfohGdkMttNdLKrzuW/2Uwo9vlu9adeQLxp8/Mek2wE/jxeDAbywqHGrt5F2QejFV/BNCnVtg+aF5HW8UqoqqHMl6wj4D1FMPQ23IVq4w1zfS+9SPbA4G1UzO3+iZolMQNHRKglalhMaCDsZ/7k1a0BLI6Yl1QTZo/F1NDpBJQZ/ycSLZ35xjGpqpJUeZK8JBHZwFI41u903ezgysRGRWAJzcF5dGOZjyoZgq3B5WpjX217NNySPg0NQpLOzJXE29cdUUnEpfMsKLfo4rvwNeZ1j9SHQXvuzCJ+Ww0ArgCqZWWkiXCgexesvJZ9yVUh+486nojAaxqgbHReKZmXSutJz1mx8RBX5sxPwV4SadxZubP3obxe6HWj2eJNm7ESeNKSI6AeXnxHvhS2CRqGl45UHuDYs=
